@startuml
participant Client
participant Controller
participant courseRepository
participant Model

Client -> Controller: POST Request: /add-courseSM
activate Controller

Controller -> courseRepository: save(course)
activate courseRepository
courseRepository --> Controller: Saved Course
deactivate courseRepository

alt Course saved successfully
    Controller -> Model: addAttribute("message", "Course added successfully.")
    Model --> Controller: Updated model
    Controller --> Client: Redirect to /schedule-manager/smv-course-success-page (with success)
else Course not saved successfully
    Controller -> Model: addAttribute("message", "Error adding course. Controller")
    Model --> Controller: Updated model
    Controller --> Client: Stay on the same page (add-courseSM) and display error
end

@enduml
